### ISSUE TITLE
I have GE smart devices and am willing to provide assistance.

### ISSUE THREAD

**Issue by bradtchapman** [simbaja/ha_gehome#109]
Hello,

I have a GE GFW650-series washer, and GFD85G-series dryer with the steam option.  And last week I just bought a GE Profile range, PGS930-series.  I already have a Raspberry Pi 4 that I use for PiHole and installed HomeBridge to connect a LiftMaster garage door opener to HomeKit.  I came across this repository for HomeAssistant while searching for a way to turn the oven light on and off with a sensor.  

I'm an IT systems engineer that is completely comfortable doing packet captures with Wireshark and using a Mac as the intermediary to 'share' the network connection to Wi-Fi, and connect the appliances through that.  If I point the washer, dryer, and range at this fake Wi-Fi network and capture everything, what would you need for me to assist you?

**Comment by barcherf5** [comment]
I'm happy to help in similar ways! I have a PVD28B-series fridge and PGB965-series gas range.

**Comment by simbaja** [comment]
Thanks for the offers of assistance, much appreciated!  Is there functionality that you're looking for that isn't currently supported for your devices?

**Comment by bradtchapman** [comment]
I wrote this issue in response to a statement on your readme page that said you have developed the code insofar as you are able with the devices at your disposal.  

Is there a functionality you think you don't have documented well enough?  Any issues that are difficult to reproduce?  Any combination of devices, hubs, and networks that have been problematic?  Was it just a very cautious and circumspect disclaimer?

**Comment by simbaja** [comment]
It's more of a disclaimer that I'm essentially unable to do much more reverse engineering (the apps use Flutter and certificate pinning, so it's a bit of a pain to figure anything out these days), so any new functionality will require help and support from the requestor.  There are a lot of devices, and a lot of functionality exposed through SmartHQ, and it's hard to figure it out without some trial and error.

For the devices you both have, I think I've got most of the functionality implemented, but there are certainly gaps in my understanding.  If you run the application from the simbaja/gehome repository, you'll see the unknown codes from your devices.  If there's something that isn't in the integration that you can identify, we can use that information to track it down.

**Comment by barcherf5** [comment]
I have a request, I guess. I'd like to be able to control the oven's set temp from HA. I handle the home automation, but my spouse also would like to be able to control things. I've promised a central location for all controls, Home Assistant. I was trying to create a text input field that fed into an automation that would turn on the oven to the specified temp when the field was changed (or a button was clicked), but I couldn't figure out how to do that. When I ran my automation, I got this error: 

'GeOven' object has no attribute 'async_turn_on'

The automation action was this:

  - device_id: <redacted>
    domain: water_heater
    entity_id: water_heater.shts179289p_upper_oven
    type: turn_on

(Side note: I think it's incredibly clever that you are treating the oven like a water heater. Outside the box thinking!)

Do I have the action configured wrong, perhaps?

I'll see what I see in the SDK output. :)

**Comment by simbaja** [comment]
I think if you just set the temperature, I've got it configured to also set the mode to bake if it's not already on.  So if you call "water_heater.set_temperature", you should get the desired behavior.

**Comment by barcherf5** [comment]
Well would you look at that! You're awesome again! :D

**Comment by barcherf5** [comment]
I don't see any unknowns for the oven I've got, but my fridge has six "FRIDGE_UNKNOWN" lines:

`2022-09-19 13:19:26,970 DEBUG    Setting ErdCode.FRIDGE_UNKONWN_1029 to b'\x01'
2022-09-19 13:19:26,970 DEBUG    Setting ErdCode.FRIDGE_UNKNOWN_1100 to b'\x02\xe2\x00\x05\xbbN/\x00'
2022-09-19 13:19:26,970 DEBUG    Setting ErdCode.FRIDGE_UNKNOWN_1101 to b'\x00\x00?9\x00\x01K\xb3\x0f\xdb\x0f\xa5\x00\x00\x04\xd0'
2022-09-19 13:19:26,970 DEBUG    Setting ErdCode.FRIDGE_UNKNOWN_1102 to b'\x00\x84\x02,\x03\x82\x00\x00\x05\\\x00\x00\x00\x00'
2022-09-19 13:19:26,971 DEBUG    Setting ErdCode.FRIDGE_UNKNOWN_1103 to b"\x00\x05\xc53%\x00%\x1b\x02\xfc \x05\x00\xf4E<'"
2022-09-19 13:19:26,971 DEBUG    Setting ErdCode.FRIDGE_UNKNOWN_1104 to b'\x00\x05\xc53\x00\t\x00\x15\x00\x00\x04t\x00\x00\x00\x00\x00\x00\x00'`

There's also some hex codes in the output that aren't explained: x100C, x100D, x1021, x1022, and x1023.

I don't see the Turbo Cool and Turbo Freeze statuses in HA, but they're there in the output. There's no setting for them in SmartHQ, so maybe that's why you didn't surface them in the UI. I don't know if that /can/ be controlled from the backend at all, but IMHO it would be such a rarely-used feature that it's probably not worth it.

**Comment by DavidSack** [comment]
I have both a GE Fridge HR159526 and a GE Oven SNFT068103Q if that would help.

**Comment by tcgoetz** [comment]
I have a GE Monarch ZDP486NDT1SS: https://www.geappliances.com/appliance/Monogram-48-Dual-Fuel-Professional-Range-with-6-Burners-and-Griddle-Natural-Gas-ZDP486NDTSS

Integrations mostly work. Some issues:
- Ovens are actually side by side, not upper/lower. Not sure if this info is available.
- Lower oven temp is always shown at 0 degrees.

Screenshot of HA device record for oven: https://goetz-ds1.quickconnect.to/d/s/rTubB2PiBjKs9Sm9AHb4FSam1oVqEB72/v2Y0kirMsbc0NU1_Dldssfw_Cn8MTJCd-Y71ANI8nDAo

Thanks for your work!

**Comment by gtbdf1** [comment]
Hi there. I have the WiFi connected Profile Opal 2.0 nugget ice maker. Let me know if there’s anything I can send over to help.

**Comment by simbaja** [comment]
Closing as stale, please open a new request if there's specific functionality needed.
