### ISSUE TITLE
Enhancement Request - GE Profile Double Oven with Air Fry - PTD7000SN3SS

### ISSUE THREAD

**Issue by CobraDunn** [simbaja/ha_gehome#146]
- Add Air Fry as mode option
- Add control of oven lights
Can provide logs and feedback.

**Comment by sdschramm** [comment]
I have the GE Profile PTS7000SN2SS (probably very similar to yours but mine is a single wall oven) and I too would like to get the Air Fry mode added into the drop down, and an entity to control the oven light. 

I'm happy to help in any way I can. Thanks!

**Comment by advisorgee** [comment]
I'd like to see the Air Fryer option added as well.

**Comment by mark-klink182** [comment]
In an older version of the integration, I was able to use the service call 'Water Heater: Set operation mode' to set the operation mode to Air Fry.  But since the last couple of updates, this is no longer possible.  I have the P2S930SEL2SS and Air Fry is not available from the oven controls but it is on the GE Smart HQ App.  The latest updates not only broke the Air Fry automation but when I use the device card in HA and set it to bake it doesn't work.  Here are the log entries.

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 280, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 707, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for 
2023-09-14 16:50:36.613 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities water_heater.d828c9112ae1_oven are missing or not currently available

The integration reports sensor data but it will not control the oven.  Using v0.6.8

**Comment by mark-klink182** [comment]
About a year ago I replaced the control board on my oven so after that, the integration showed 2 ovens.  I disabled the old oven and everything was still working up until I updated the integration along with HA.  See my last post above.

I uninstalled the add-on and reinstalled it.  The errors went away along with the old oven, and I was able to use an automation to set Air Fry mode even though it is not a default in the list.

**Comment by louishleon** [comment]
> In an older version of the integration, I was able to use the service call 'Water Heater: Set operation mode' to set the operation mode to Air Fry. But since the last couple of updates, this is no longer possible. I have the P2S930SEL2SS and Air Fry is not available from the oven controls but it is on the GE Smart HQ App. The latest updates not only broke the Air Fry automation but when I use the device card in HA and set it to bake it doesn't work. Here are the log entries.
> 
> Traceback (most recent call last): File "/config/custom_components/ge_home/update_coordinator.py", line 280, in on_device_update entity.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 707, in async_write_ha_state raise RuntimeError(f"Attribute hass is None for {self}") RuntimeError: Attribute hass is None for 2023-09-14 16:50:36.613 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities water_heater.d828c9112ae1_oven are missing or not currently available
> 
> The integration reports sensor data but it will not control the oven. Using v0.6.8

I'm also experiencing the same issue where the entity does not have control to bake or use the other modes.  It can only read.

**Comment by simbaja** [comment]
Happy to add if someone can help with the mode, my oven doesn't have this feature.  Please head to the [sdk](https://github.com/simbaja/gehome) if you have time and inclination to assist.

**Comment by mark-klink182** [comment]
Attached are websocket_example.py logs.  After initially running it, then and turning the oven off, I then used the SmartHQ app to turn the oven on Air Fry @ 400.  This is where the logs start.  When trying to use Home Assistant to turn on Air Fry I will receive the following error in the HA logs.  

Error: Operation mode Air Fry is not valid for water_heater.d828c9112ae1_oven. Valid operation modes are: Off, Baked Goods, Convection Roast, Frozen Pizza Multi, Bake, Conv. Multi-Bake, Frozen Snacks Multi, Frozen Pizza, Frozen Snacks

[2024-12-04 173315,890 DEBUG.log](https://github.com/user-attachments/files/18014911/2024-12-04.173315.890.DEBUG.log
