### ISSUE TITLE
Fabric softener level doesn't exist

### ISSUE THREAD

**Issue by rlippmann** [simbaja/ha_gehome#158]
In addition to the incorrect washer detergent levels I've noted in [my previous issue](https://github.com/simbaja/ha_gehome/issues/126), I've also noticed that the fabric softener level isn't showing up (don't think it ever has).

Hopefully my data dump from that issue might help here too.

**Comment by simbaja** [comment]
Looking at it, I'm going to bet that the issues are linked to #126.  I'm guessing that the real issue is that the tank level is probably a multi-valued code (i.e. both tanks are represented in one value).  I'm going to close this one and leave the other one open, but I'm not sure how to debug this as I don't have a laundry unit.
