### ISSUE TITLE
Unknown Unit Type: 0000000B, using default

### ISSUE THREAD

**Issue by ziptbm** [simbaja/ha_gehome#204]
`Logger: gehomesdk.erd.converters.specialized.erd_unit_type_converter
Source: runner.py:186
First occurred: 14:21:17 (15 occurrences)
Last logged: 14:28:18

Unknown Unit Type: 0000000B, using default`

This error shows up with every reboot and I believe it's related to this integration.  I'm not sure what specifically is impacted by it, but reporting it nonetheless.  I have 3 SmartHQ devices (GE washing machine, GE dryer, and Cafe Fridge).  Please let me know what would be helpful to grab for this error.

**Comment by simbaja** [comment]
I think they've been changing some of the values for this field in newer devices.  We don't use it in HASS, so it shouldn't cause any issues for you, but let me know if you see something amiss.

**Comment by LoganInTX** [comment]
I have a similar message that shows up thousands of times as a warning in my HASS logs but for unit type 00000013
Any idea on where to fix this in the code so that it doesn't flood my logs?
******************
Logger: gehomesdk.erd.converters.specialized.erd_unit_type_converter
Source: runner.py:190
First occurred: 11:29:23 AM (4299 occurrences)
Last logged: 11:39:23 AM

Unknown Unit Type: 00000013, using default
*******************

**Comment by ziptbm** [comment]
@simbaja is there anything I can do to suppress this particular one?  e.g. I've had 9571 occurrences in the last 3 days.

Logger: gehomesdk.erd.converters.specialized.erd_unit_type_converter
Source: runner.py:190
First occurred: July 26, 2024 at 07:57:44 (9571 occurrences)
Last logged: 15:59:44

Unknown Unit Type: 0000000B, using default
