### ISSUE TITLE
Re-authentication Popup Fails (and Missing Labels)

### ISSUE THREAD

**Issue by thomasmaxson** [simbaja/ha_gehome#246]
Home Assistant Core - 2024.4.2
Home Assistant Supervisor - 2024.04.0

With the latest update, I required a re-authentication. I noticed that the form fields contain no guiding information (email/username vs password).

![image](https://github.com/simbaja/ha_gehome/assets/302071/aae2cecb-2ea8-43aa-ae1d-c8c52777de9b)

**Comment by al922816** [comment]
Please try the fix described in the following issue. This fixed it for me:

https://github.com/simbaja/ha_gehome/issues/244

**Comment by julio8a** [comment]
> Please try the fix described in the following issue. This fixed it for me:
> 
> #244

I can confirm this works!

**Comment by darkpixel** [comment]
Doesn't work for me.
Changing my password on the one linked site had *zero* effect on my cell phone's ability to sign in, so I'm not sure exactly who I gave my creds out to...but the old creds and the new creds don't work.  Home Assistant just keeps saying ```Invalid authentication```.

**Comment by brystmar** [comment]
> Fixed. I decided to approach it another way. From the SmartHQ app on my phone, I went into account management, entered my password, changed my password....and at the end of the change password process it asked me to agree to new terms and conditions. After I did that it started working. Not sure why it wouldn't just pop up in my app or on the website to ask me to agree instead of going through a password change to get the new TOS. Weird.

I was having the same problem.  I changed my pw on the desktop site but was still unable to authenticate via HA.  The desktop site made no mention about accepting new TOS, so I opened the mobile app.  Nothing there, so I logged out of the app and logged back in.  The app required accepting the new TOS upon login.  After doing this, I was able to successfully authenticate via HA.  Annoying stuff, GE.

@simbaja: Does the SmartHQ auth service return a distinct error code for auth failures due to TOS acceptance?  Would be nice if they did, but I'm not holding my breath.

**Comment by kodeypatterson** [comment]
> Fixed. I decided to approach it another way. From the SmartHQ app on my phone, I went into account management, entered my password, changed my password....and at the end of the change password process it asked me to agree to new terms and conditions. After I did that it started working. Not sure why it wouldn't just pop up in my app or on the website to ask me to agree instead of going through a password change to get the new TOS. Weird.

This worked for me!

**Comment by mopwr** [comment]
Signed out of app and back in to get the new terms of service screen, accepted that and then signin worked again in home assistant. (had to do this on the app, website did not work)

**Comment by mrgasket** [comment]
You guys are awesome! Fixed it on my instance as well. Your mileage may vary, but here is how it went for me if it helps anyone else.  Steps I took were: 

1. Attempted to login from browser at [https://www.geappliances.com/](url) .
2. Got prompted to change password per new GE policy.
4. Reset password through browser.
5. Reboot HA.
6. Reconfigured integration with new credentials... failed as before.
7. Opened GE's "Smart HQ" app on Android device. Navigated to General Settings>Manage Account.
8. Was prompted to log in. Used new credentials. 
9. Was greeted with a TOS prompt and agreed to new TOS .
10. "Reload"ed HA... Failed as before (Someone else may be able to verify, I think this failed due to "Reload"  only hits Automatons, Scripts, etc but does not reload Integrations).
11. "Reboot"ed HA from power menu and integration worked like a champ with no errors. FIXED!

**Comment by Supreme-Bob** [comment]
Interesting the app and the site seem to be separate accounts now. I just tested resetting passwords on the app and it doesn't change it on the geappliances.com site same goes the other way around. Mine have 2 different passwords with the same email address now.

**Comment by simbaja** [comment]
Thanks for all the debugging of this problem.  I've added a note to the pinned issue so that others can find them should there be continued auth weirdness.
