### ISSUE TITLE
Fisher & Paykel RF605QDAA (Quad Door) Fridge

### ISSUE THREAD

**Issue by VlastiBroucek** [simbaja/ha_gehome#267]
The fridge is not displaying properly. This is what I see in the GE App:

![Screenshot_20240624_183230_Smart HQ](https://github.com/simbaja/ha_gehome/assets/156775557/d7d0168e-7f60-440c-a2a1-886769d30da7)

This is what I see in HA:

![image](https://github.com/simbaja/ha_gehome/assets/156775557/6718eb84-a309-4f4f-9a59-c15706580d97)

The top is double door fridge, bottom left is freezer and bottom right can be changed between:  Freeze,  Soft Freeze, Chill and Fridge

If you tell me what you need and how to get it, I will provide more information...

**Comment by bamcauliffe** [comment]
I have the same fridge & the same information (identical) being reported. 
I am also happy to provide logs to help with the development of this integration. 
It would also be great if there was current temperatures of the compartments. 
My freezer has stopped working and is about +10 Deg C despite the -18 Deg C set point. I have put my Netatmo monitors in the compartments to  monitor the temperatures. The Fisher Paykel tech is booked in for the 10-October.

**Comment by VlastiBroucek** [comment]
I think that the integration can provide only what's in the native App. Tbh, I don't think it provides current temperatures...

**Comment by bamcauliffe** [comment]
I expect that might be the case. However with my Daikin air conditioners, the app does not have the compressor speed, but the Home Assistant integration does have compressor speed, which I have found useful. I expect the current temperatures would not been in the SmartHQ app as customers might be concerned with the temperature not being exactly on the set point, however as an engineer, I understand that the temperature will fluctuate even under great control.

**Comment by VlastiBroucek** [comment]
> I expect that might be the case. However with my Daikin air conditioners, the app does not have the compressor speed, but the Home Assistant integration does have compressor speed, which I have found useful. I expect the current temperatures would not been in the SmartHQ app as customers might be concerned with the temperature not being exactly on the set point, however as an engineer, I understand that the temperature will fluctuate even under great control.

Yes, one would reasonably expect that here must be current temperature reading somewhere in the fridge. After all, how else would it maintain the set temperature? But if it is exposed to API/Cloud or whatever SmartHQ is using is so far a mystery. 

If you find something, please let me know. I too had the freezer fail and knowing that earlier could safe some food and time with servicing.

**Comment by FPA-ChrisLaird** [comment]
Hi guys, Fpa ref products do not expose compartment temperatures to the app as we don't want people getting upset when their target temp != compartment temp.  You'd be surprised how many people get upset when their product temp doesn't exactly match the target temp at all times.

Internally the product knows the compartment temperatures.

**Comment by VlastiBroucek** [comment]
> Hi guys, Fpa ref products do not expose compartment temperatures to the app as we don't want people getting upset when their target temp != compartment temp. You'd be surprised how many people get upset when their product temp doesn't exactly match the target temp at all times.
> 
> Internally the product knows the compartment temperatures.

Exactly what I was expecting.  If I was at F&P, I would be developing SMART functionality in a way that technicians could possible remotely troubleshoot. So, there must be a backdoor somewhere, or a way to read these... Perhaps they even go to the cloud and are just not exposed to the App... Time to set up a sniffer and capture all the traffic... Nice hack challenge... 🤣😂😁

**Comment by FPA-ChrisLaird** [comment]
> > Hi guys, Fpa ref products do not expose compartment temperatures to the app as we don't want people getting upset when their target temp != compartment temp. You'd be surprised how many people get upset when their product temp doesn't exactly match the target temp at all times.
> > Internally the product knows the compartment temperatures.
> 
> Exactly what I was expecting. If I was at F&P, I would be developing SMART functionality in a way that technicians could possibly troubleshoot remotely. So, there must be a backdoor somewhere, or a way to read these... Perhaps they even go to the cloud and are just not exposed to the App... Time to set up a sniffer and capture all the traffic... Nice hack challenge... 🤣😂😁

There isn't a service mode that exposes these values to wifi, yet.  There will be in the future though ;)

**Comment by bamcauliffe** [comment]
Per my original message, I have had a problem with my Quad door Fisher & Paykel fridge recently.
In order to see what the temperatures are doing in the fridge, I have had to put my Netamo sensors in each compartment.
The fridge is doing as expected with a set point of 3 Deg C and the actual varying between 3 & 4 Deg C. The variable temperature compartment with a set point of -18 Deg C does vary a lot. It does get down to about -15 Deg C but does get close to zero. The big problem is the freezer with the set point being -18 Deg C but the current temperature being about +11 Deg C (yes positive). Has been like this for nearly 2 weeks. The Fisher Paykel technician should be here Thursday to look at it. I was hoping to have some actual temperatures in the app or Home Assistant, but I do understand customers would be concerned about normal fridge/freezer temperature behaviour.

I plan to have the sensors back in the compartments for 24hrs before the Technician is due to arrive.

I also had the problem that the freezer was well and truly defrosted before I knew there was a problem. An alarm on the fridge or app would have been helpful. I have had lots to do with alarming in my work. I understand that not getting an alarm right can cause a lot more problems. My thoughts on an alarm would be something like the compartment temperature has not been within 4 degrees C of set point for 6 hours. So for my freezer, with a set point of -18 Deg C, after it was warmer than -14 Deg C for 6 hours would have alarmed. Even if the notification was not active on the fridge or in the app, if it was available in Home Assistant would have helped.

The app has lot of potential. I do understand that more information for those who do not understand could be very problematic. 
I look forward to see how this develops to help service technicians and end users.

**Comment by VlastiBroucek** [comment]
That's exactly what happened to my fridge on 8 March (that one was not having the smart module in). I was lucky that technician came next day and quickly determined that the problem was in sealed internal part and the only possible fix was to replace the fridge under warranty. That was quick... But then it took **52 days** of waiting and over 7 hours on the phone with various parts of F&P, shipping company and local delivery/service person to have the replacement in my home... 
So good luck to you...
Disclaimer: I have had various F&P products since 1992 and this was the first one that had a problem, ever. I hope the experience above was one off - just unlucky combination of bad luck (apparently the replacement fridge was shipped to wrong address initially), Easter, Anzac Day and me being in Tasmania.
