### ISSUE TITLE
Several Oven modes missing 

### ISSUE THREAD

**Issue by jazzmonger** [simbaja/ha_gehome#55]
I have a brand new GE Monogram wall oven. The integration installs and works (mostly).  It has several modes that aren't available in the integration.  Specifically:

Warm
Proof
Broil

these are available in the oven menus but not in the integration.... any thoughts here? I use the warm mode most often but there's no way to access it via home assistant...

jeff

**Comment by simbaja** [comment]
Unfortunately, they don't support all the modes from what I can see.  I've added everything that they supported from the official app, which doesn't include those three.  I actually tried adding all the modes, but when you try to set it, it doesn't respond, so reverted to the limited list from the app.  So, I think we're stuck here due to limited support.  I did read in some documentation somewhere that they didn't enable at least broil remotely because of some sort of safety concern (seems odd, since in theory everything is a safety concern, but not my decision).
