### ISSUE TITLE
Turn off oven

### ISSUE THREAD

**Issue by carinconc** [simbaja/ha_gehome#72]
Is there a way to turn off an oven using your integration? Thank you in advance for your help.

**Comment by briandking** [comment]
I can confirm I have the same issue. It appears to be because my oven shows up as a water heater class device:

`water_heater.smsr543028p_oven`

and `./entities/common/ge_water_heater.py` doesn't have a definition for async_turn_off like these other types of devices do:

```
./entities/common/ge_climate.py
./entities/common/ge_erd_light.py
./entities/common/ge_erd_switch.py
```

My oven is a Model CCHS900P3M2D1
Are there any logs or debugging info I could collect to help?

**Comment by mikekay1** [comment]
Try deleting the appliance and readding it, They have made alot of back end changes, and its possible that yours is running in a legacy mode.

**Comment by mikekay1** [comment]
This is the case for me as well :(

![image](https://user-images.githubusercontent.com/52670539/172683914-d6c28db2-ca71-4347-82a9-4a3089458907.png)

**Comment by briandking** [comment]
> Try deleting the appliance and readding it, They have made alot of back end changes, and its possible that yours is running in a legacy mode.
> 
> edit: on the smartHQ app that is...

Yes, the oven works fine with the GE SmartHQ and with Google/Alexa, it's just in Home Assistant it's a read-only device.

**Comment by mikekay1** [comment]
Also I got the option to change the temp and power only once remote enabled was on. On and off works now for me.

**Comment by briandking** [comment]
> Also I got the option to change the temp and power only once remote enabled was on. On and off works now for me.

On/Off works for you in **_Home Assistant_** now?

**Comment by mikekay1** [comment]
> > Also I got the option to change the temp and power only once remote enabled was on. On and off works now for me.
> 
> On/Off works for you in **_Home Assistant_** now?

Yessir it does!

**Comment by carinconc** [comment]
@mikekay1: Can you share the procedure to turn on/off the oven in Home Assistant? I have deleted and re-added my oven both in SmartHQ and Home Assistant. However, I do not have the option to turn the oven on/off. Thanks in advance for your help.

**Comment by mikekay1** [comment]
![Screenshot_20220621-112247_Home Assistant](https://user-images.githubusercontent.com/52670539/174837398-a1181b53-8028-4178-b286-7668d15a05fa.jpg)

From image above I simply select off, remote enabled has to be on for me to be able to use that drop down and temp adjustment...

Hope this helps!

**Comment by briandking** [comment]
Mine started working after I upgraded Home Assistant to "Home Assistant Core 2022.6.6". I didn't note which version I was coming from but it was probably 3-6 months old.

**Comment by briandking** [comment]
I think part of the confusion here is that this chain started about automations, and automating the oven is different than most other devices.
The obvious way to turn on the oven is the same as other devices:
- Action Type = Device
- Device = {the oven device}
- Action = Turn on

That path will lead to the error this report started with.

For future people finding this, the way to turn on the over from an automation is:
- Action Type = Call Service
- Service = Water Heater: Set Temperature
- Target = Choose Entity and select your oven
- Temperature = type the temperature in Celsius (the slider only goes to 100 probably because it's based on a water heater)
- Check the box for "Operation Mode" and type "Bake" in the field
  - Other valid values can be found in the "operation_list" attribute of your oven entity. E.g. my list is "Off, Frozen Pizza, Convection Roast, Frozen Pizza Multi, Frozen Snacks Multi, Conv. Multi-Bake, Baked Goods, Frozen Snacks, Bake"

That might be worth adding to documentation somewhere?

**Comment by robpneu** [comment]
> That might be worth adding to documentation somewhere?

I agree, this should be documented somewhere, I only figured it out a few months ago after a lot of searching. I’ve started setting up some very useful automation scripts, however I cannot get the “Operation Mode” to work; it turns on but it’s always set to “Bake”, regardless of what I put in that box. Any ideas?

**Comment by briandking** [comment]
I hadn't actually tried anything other than Bake until now. 
I seem to only be able to set the mode properly with a follow up call like you describe, and only when selecting an entity, not the device, which results in working YAML like this:

```
service: water_heater.set_operation_mode
data:
  operation_mode: 'Frozen Pizza'
target:
  entity_id:
    - water_heater.smsr543028p_oven
```

If you select a device (like I said previously) the automations UI generates YAML like this instead
```
service: water_heater.set_operation_mode
data:
  operation_mode: 'Frozen Pizza'
target:
  device_id: 18966c9517cff83e020eb90f2450440e
```
Which when fed into developer tools, returns the error
```
Failed to call service water_heater.set_operation_mode. extra keys not allowed @ data['device_id']. Got None
```

It seems like the service ```water_heater.set_operation_mode``` requires an entity_id.

**Comment by yohaas** [comment]
`service water_heater.set_operation_mode` can also be used to turn the oven off:

```
action:
  - service: water_heater.set_operation_mode
    data:
      operation_mode: "Off"
    target:
      entity_id: water_heater.snzt005277q_oven
```
